### PR TITLE
add ISO-8601 ToJSON, FromJSON instances

### PR DESCRIPTION
**Pull request by faineance**
( also upgrade stack resolver to lts-10.0 )

### CODE REVIEW

**Comment by sdiehl** [comment]
We should bump the version as well.

**Comment by tdietert** [comment]
actually tho can you add a to/fromjson roundtrip test which is almost idential to:
https://github.com/adjoint-io/datetime/blob/master/test/Test.hs#L163

just replacing `S.encode` and `S.decode` with `Data.Aeson.encode` and `Data.Aeson.decode`?

**Comment by faineance** [comment]
Ready to be merged

**Comment by sdiehl** [comment]
Brilliant, nice work.

**Pull request merged**
